 version: '3.8'
 services:
          app:
              build:
                  context: .
                  dockerfile: Dockerfile
              container_name: psinage2
              stdin_open: true
              tty: true

